AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Swagger Spring API written with SpringBoot with the aws-serverless-java-container
  library
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cobiscorp.auth.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://cobis-openapi-poc/21af0690183b4f729a7a2cdd15db66ca
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  SwaggerSpringApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth
    Export:
      Name: SwaggerSpringAPI
