AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Swagger Spring API written with SpringBoot with the aws-serverless-java-container
  library
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cobiscorp.auth.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://cobis-openapi-poc/6a81fd2698ae84252f498c354bc3ca42
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
