AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Swagger Spring API written with SpringBoot with the aws-serverless-java-container
  library
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AuthLambda
      Handler: com.cobiscorp.auth.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://cobis-openapi-poc/643521482dea6ddd163697cbc34d5f8d
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
