AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Swagger Spring API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AuthLambda
      Handler: com.cobiscorp.auth.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/auth-1.0.0-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
#      Events:
#        MyApi:
#          Type: Api
#          Properties:
#            Path: /{proxy+}
#            Method: any
#            RestApiId: !Ref MyApi

#  Crear APIGateway con documentación Swagger   
#  MyApi:
#    Type: AWS::ApiGateway::RestApi
#    Properties:
#      BodyS3Location:
#        Bucket: cobis-openapi-poc
#        Key: specs/COBISAuthorizationAPI.yaml

